name: build-release

on:

  pull_request:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '6.X.X'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5.0.1

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64 make tar

      - name: Compile (pack-release.sh)
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          chmod +x ./pack-release.sh
          ./pack-release.sh "${VERSION}"

      - name: Get Previous Tag
        id: previous_tag
        run: |
          tag=$(gh release list --limit 1 | grep -v 'Latest' | awk '{print $1}')
          echo "::set-output name=tag::${tag}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Tag
        id: create_tag
        uses: actions/github-script@v8.0.0
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.version.outputs.version }}',
              sha: context.sha
            })

      - name: Write Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v6.0.1
        with:
          configuration: ".github/build-changelog.json"
          fromTag: ${{steps.previous_tag.outputs.tag}}
          toTag: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: Release ${{ steps.version.outputs.version }}
          path: mo2installer-${{ steps.version.outputs.version }}.tar.gz
          if-no-files-found: error
          retention-days: 30

      - name: Create Release
        uses: softprops/action-gh-release@v2.4.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: mo2installer-${{steps.version.outputs.version}}.tar.gz
          tag_name: ${{steps.version.outputs.version}}
          body: ${{steps.changelog.outputs.changelog}}
          token: ${{secrets.GITHUB_TOKEN}}